#!/bin/sh /etc/rc.common
#file: /etc/init.d/rrm_nr
## Based on: https://forum.openwrt.org/t/how-does-rrm-work/32635/68

START=99

NAME=rrm_nr
USE_PROCD=1

start_service() {
	#todo skip if nr is disabled for interface, skip disabled interface etc.

	procd_open_instance
	procd_set_param command /bin/sh "/usr/bin/rrm_nr"
	#https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?search=5247
	procd_open_data
	json_add_object "mdns"
	local service proto port
	service="rrm_nr"
	proto="udp"
	port=5247
	json_add_object "${service}_$port"
	json_add_string "service" "_$service._$proto.local"
	json_add_int port "$port"
	json_add_array txt

	OIFS=$IFS
	IFS=$'\x0a'

	for value in $(ubus list hostapd.wlan*); do
		json_add_string "" "$(/bin/ubus call ${value} rrm_nr_get_own | /usr/bin/jsonfilter -e '$.value')"
	done

	IFS=$OIFS

	json_select ..
	json_select ..
	json_close_object
	procd_close_data
	procd_open_trigger
	procd_add_config_trigger "config.change" "wireless" /etc/init.d/rrm_nr restart
	procd_close_trigger
	procd_close_instance
}

boot() {
	sleep 30
	start
}

service_triggers() {
	procd_add_reload_trigger wireless
}